# Generated by Django 4.0 on 2022-07-04 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0005_rename_thread_name_chatmodel_room_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmodel',
            name='message_type',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
